//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoTroBenhNhan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class baiViet
    {
        public int idbaiViet { get; set; }
        public Nullable<int> idLoai { get; set; }
        public string TenBaiViet { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public string hinhAnhBaiViet { get; set; }
        public string tieuDe { get; set; }
        public string noiDungTieuDe { get; set; }
        public string anhMinhHoa { get; set; }
        public string tieuDe1 { get; set; }
        public string noiDungTieuDe1 { get; set; }
        public string anhMinhHoa1 { get; set; }
        public string tieuDe2 { get; set; }
        public string noiDungTieuDe2 { get; set; }
        public string anhMinhHoa2 { get; set; }
        public string tieuDe3 { get; set; }
        public string noiDungTieuDe3 { get; set; }
        public string anhMinhHoa3 { get; set; }
        public string tieuDe4 { get; set; }
        public string noiDungTieuDe4 { get; set; }
        public string anhMinhHoa4 { get; set; }
        public string tieuDe5 { get; set; }
        public string noiDungTieuDe5 { get; set; }
        public string anhMinhHoa5 { get; set; }
        public string moTaNgan { get; set; }
    
        public virtual LoaiBlog LoaiBlog { get; set; }
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
