//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoTroBenhNhan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Benhvien()
        {
            this.Thongtinhientang = new HashSet<Thongtinhientang>();
        }
    
        public long mabenhvien { get; set; }
        public string tenbenhvien { get; set; }
        public string Anh { get; set; }
        public string DiaChi { get; set; }
        public string Sđt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thongtinhientang> Thongtinhientang { get; set; }
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
