//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoTroBenhNhan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khieunai
    {
        public int MaKN { get; set; }
        public string LinkBaiviet { get; set; }
        public string NoidungKN { get; set; }
        public Nullable<int> Matk { get; set; }
    
        public virtual Taikhoan Taikhoan { get; set; }
    }
}
