//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoTroBenhNhan.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taikhoan()
        {
            this.Khieunai = new HashSet<Khieunai>();
            this.Thongtinbenhnhan = new HashSet<Thongtinbenhnhan>();
            this.Thongtinhientang = new HashSet<Thongtinhientang>();
        }
    
        public int Matk { get; set; }
        [Required(ErrorMessage = "Nhập Email")]
        [StringLength(100, ErrorMessage = "Email tối thiểu 6 kí tự ", MinimumLength = 6)]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Vui lòng nhập đúng định dạng email")]
        public string TenDN { get; set; }
        [Required(ErrorMessage = "Nhập mật khẩu")]
        //[DataType(DataType.Password)]
        public string Matkhau { get; set; }
        public string Anhdaidien { get; set; }
        public string Quyenadmin { get; set; }
        public string Cccdtruoc { get; set; }
        public string Cccdsau { get; set; }
        [Required(ErrorMessage = "Nhập số điện thoại")]
        [StringLength(20, ErrorMessage = "Số điện thoại phải đúng 10 chữ số", MinimumLength = 5)]
        public string Sdt { get; set; }
        public string Quyendangbai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khieunai> Khieunai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thongtinbenhnhan> Thongtinbenhnhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thongtinhientang> Thongtinhientang { get; set; }
        
        public string Xacnhanmatkhau { get; set; }

        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
