//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoTroBenhNhan.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Thongtinbenhnhan
    {
        public long Mabaiviet { get; set; }
        [Required(ErrorMessage = "Vui lòng Nhập họ tên bệnh nhân ")]
        public string HotenBN { get; set; }
        public string Hinhanh { get; set; }
        public string Noidungdaydu { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại ")]
        public Nullable<int> Sdt { get; set; }
        public string Linkfb { get; set; }
        public string Linkzalo { get; set; }
        public string Diachicuthe { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn tỉnh bệnh tình ")]
        public Nullable<int> Mabenh { get; set; }
        public Nullable<int> Matk { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn tỉnh thành phố")]
        public Nullable<long> Tinhthanhpho { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn quận huyện")]
        public Nullable<long> Quanhuyen { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn xã phường")]
        public Nullable<long> XaPhuong { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
    
        public virtual QuanHuyen QuanHuyen1 { get; set; }
        public virtual Taikhoan Taikhoan { get; set; }
        public virtual Trinhtangbenh Trinhtangbenh { get; set; }
        public virtual TinhThanhPho TinhThanhPho1 { get; set; }
        public virtual XaPhuong XaPhuong1 { get; set; }
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
