//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoTroBenhNhan.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Thongtinhientang
    {
        public int MaHT { get; set; }
        [Required(ErrorMessage = "Chọn bệnh viện")]
        public Nullable<long> maBV { get; set; }
        public string Hotennguoihien { get; set; }
        [Required(ErrorMessage = "nhập nội dung ")]
        public string Noidunghientang { get; set; }
        public Nullable<System.DateTime> Ngaytaobaiviet { get; set; }
        public Nullable<int> Matk { get; set; }
        [Required(ErrorMessage = "Chọn bộ phận")]
        public Nullable<int> Mabenh { get; set; }
    
        public virtual Benhvien Benhvien { get; set; }
        public virtual Taikhoan Taikhoan { get; set; }
        public virtual Trinhtangbenh Trinhtangbenh { get; set; }
    }
}
